DAOS-15695: golang update to 1.22.3
daos-stack/go-build-toolchain pull request #25
Opened 2024-05-09 05:57 UTC by grom72

2024-05-09 14:39 UTC, JohnMalmberg approved these changes, later dismissed

2024-05-13 16:42 UTC, brianjmurrell requested changes

2024-05-13 16:42 UTC, brianjmurrell commented on go.spec
> +* Thu Jan 18 2024 Tomasz Gromadzki <tomasz.gromadzki@intel.com> - 1.22.3-1
Need to update this datestamp.

2024-05-14 18:05 UTC, grom72 commented on go.spec
> +* Thu Jan 18 2024 Tomasz Gromadzki <tomasz.gromadzki@intel.com> - 1.22.3-1
Done

2024-05-14 19:52 UTC, brianjmurrell commented
Hrm.  The [downstream testing](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-25-master/7/pipeline/182) is not using this PR's packages in it's RPM build setup.  I suspect that's because it's being set with the `CI_PR_REPOS` and not the `PR-repos:` commit pragma.  We are probably only checking and using the latter.

Probably/perhaps https://github.com/daos-stack/packaging/blob/1567c66dd52acdab63e50009115f2acde9212bef/Makefile_packaging.mk#L38 needs to check for and prefer the `CI_PR_REPOS` environment variable if it exists.  Could you try patching the `packaging/` subdir in this pr with:

```diff
--- a/Makefile_packaging.mk
+++ b/Makefile_packaging.mk
@@ -35,7 +35,11 @@ TEST_PACKAGES ?= ${NAME}
 # unfortunately we cannot always name the repo the same as the project
 REPO_NAME ?= $(NAME)
 
+ifneq ($(CI_PR_REPOS),)
+PR_REPOS                 ?= $(CI_PR_REPOS)
+else
 PR_REPOS                 ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos: *\(.*\)/\1/p')
+endif
 LEAP_15_PR_REPOS         ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-leap15: *\(.*\)/\1/p')
 EL_7_PR_REPOS            ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-el7: *\(.*\)/\1/p')
 EL_8_PR_REPOS            ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-el8: *\(.*\)/\1/p')
```

on the hope that `CI_PR_REPOS` is exposed to the environment that `make` is running in?

If that doesn't work we might have to dig a bit deeper and see if that environment variable is set in the environment this script is running in: https://github.com/daos-stack/pipeline-lib/blob/31dfdfe7ae64715e2da0fadffaa0a8c3a4be3378/vars/buildRpm.groovy#L73-L74.  But let's just start with the patch above.  You may want to create a new PR based on this PR to do that testing in so as not to muck up this PR.

2024-05-14 19:53 UTC, brianjmurrell requested changes
LGTM, but I'm just going to -1 until we work out the downstream testing issue.

2024-05-15 16:57 UTC, brianjmurrell commented
@grom72 My apologies.  I wasn't considering where `CI_PR_REPOS` needs to be evaluated.  That needs to happen in the daos repo, not this one.

Can you create a daos PR and apply the below patch to it in addition to it being applied here?

> ```diff
> --- a/Makefile_packaging.mk
> +++ b/Makefile_packaging.mk
> @@ -35,7 +35,11 @@ TEST_PACKAGES ?= ${NAME}
>  # unfortunately we cannot always name the repo the same as the project
>  REPO_NAME ?= $(NAME)
>  
> +ifneq ($(CI_PR_REPOS),)
> +PR_REPOS                 ?= $(CI_PR_REPOS)
> +else
>  PR_REPOS                 ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos: *\(.*\)/\1/p')
> +endif
>  LEAP_15_PR_REPOS         ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-leap15: *\(.*\)/\1/p')
>  EL_7_PR_REPOS            ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-el7: *\(.*\)/\1/p')
>  EL_8_PR_REPOS            ?= $(shell git show -s --format=%B | sed -ne 's/^PR-repos-el8: *\(.*\)/\1/p')
> ```

Once you have that daos PR, you can add a new (empty, even) commit to this PR with the following in the commit message:

```
Test-master-branch: <daos-PR's/branch>
```

Note that `<daos-PR's/branch>` is the branch name (i.e. `grom72/use-CI_PR_REPOS`), not a PR-####.  You can push the updated commit to this PR as soon as you push the daos PR.  You don't need to wait for that PR to complete (or even be in) CI.

2024-05-21 06:48 UTC, grom72 commented
DAOS pipeline adjusted in https://github.com/daos-stack/daos/pull/14387

2024-06-13 16:30 UTC, JohnMalmberg approved these changes

2024-06-13 17:02 UTC, ryon-jensen approved these changes

2024-06-15 20:23 UTC, ryon-jensen commented
[Build 23](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-25-release-2.6/23/pipeline/) had a valgrind error in NLT. @grom72 created a fix (suppression file). Then [build 26](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-25-release-2.6/26/pipeline) with the fix applied passed NLT but had a failure in HW tests. These failures look unrelated to a go package update. I think this should be okay to land now.

2024-06-17 06:22 UTC, grom72 commented
All HW tests passed in [Build 23](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-go-build-toolchain-PR-25-release-2.6/23/pipeline) (No changes between build 23 and 26)

2024-06-17 13:53 UTC, merged